const infoPinesData = {   

    "BT0": { categoria: "power", descripcion: "BOOT0: Selección de modo de arranque (High = System Memory / Low = Flash)." },
    "3V3": { categoria: "power", descripcion: "VCC: Salida de alimentación regulada a 3.3V." },
    "GND": { categoria: "power", descripcion: "GND: Referencia de tierra común (0V)." },
    "SWDIO": { categoria: "debug", descripcion: "SWD Data: Entrada/Salida de datos para depuración y carga de código." },
    "SWCLK": { categoria: "debug", descripcion: "SWD Clock: Señal de reloj para la interfaz de depuración." },

    "BLK": { categoria: "timers", descripcion: "Backlight: Control de la retroiluminación de la pantalla (PWM para regular brillo)." },
    "DC": { categoria: "com", descripcion: "Data/Command: Selector para indicar si se envían datos (píxeles) o comandos de configuración." },
    "SDO": { categoria: "com", descripcion: "Serial Data Out (MISO): Salida de datos desde la pantalla hacia el microcontrolador." },
    "CS": { categoria: "com", descripcion: "Chip Select: Pin de habilitación. Activa la comunicación con este periférico específico." },
    "SCL": { categoria: "com", descripcion: "Serial Clock: Señal de reloj para sincronizar la transmisión de datos SPI." },
    "SDI": { categoria: "com", descripcion: "Serial Data In (MOSI): Entrada de datos desde el micro hacia la pantalla." },

    "5V": { categoria: "power", descripcion: "VCC 5V: Entrada de alimentación externa (5V) o salida regulada cuando la placa está conectada por USB. Ideal para alimentar sensores o módulos de potencia." },
    "PD8": { categoria: "com", descripcion: "GPIO / FSMC_D13: Pin de datos para memorias externas o pantallas paralelas." },
    "PD10": { categoria: "com", descripcion: "GPIO / FSMC_D15: Pin de datos de alta velocidad para bus de memoria." },
    "PD12": { categoria: "timers", descripcion: "TIM4_CH1: Salida de Timer 4. Útil para PWM (control de motores o LEDs)." },
    "PD14": { categoria: "timers", descripcion: "TIM4_CH3: Salida de Timer 4. Canal de PWM adicional." },
    "PC6": { categoria: "timers", descripcion: "TIM8_CH1: Timer de control avanzado. Ideal para inversores o control de motores trifásicos." },
    "PC8":  { categoria: "timers", descripcion: "TIM8_CH3: Timer de control avanzado, canal 3." },
    "PA8": { categoria: "power", descripcion: "MCO: Master Clock Output. Permite sacar la señal de reloj del micro para sincronizar otros integrados." },
    "PA10 RX1": { categoria: "com", descripcion: "USART1_RX: Recepción de datos serie (UART). Pin crítico para comunicación con PC." },
    "PA12": { categoria: "com", descripcion: "USB_DP: Línea de datos positiva (D+) para el puerto USB nativo." },
    "PC10": { categoria: "com", descripcion: "UART4_TX / SDIO_D2: Transmisión de datos serie o bus de datos para tarjeta SD." },
    "PC12": { categoria: "com", descripcion: "UART5_TX / SDIO_CK: Transmisión de datos serie o señal de reloj para tarjeta SD." },
    "PD1": { categoria: "com", descripcion: "CAN1_TX: Transmisión de bus CAN. Estándar industrial para comunicación robusta." },
    "PD3": { categoria: "com", descripcion: "USART2_CTS: Control de flujo para comunicación serie estable." },
    "PD5": { categoria: "com", descripcion: "USART2_TX: Transmisión de datos serie (UART) del segundo puerto." },
    "PD7": { categoria: "com", descripcion: "USART2_CK: Señal de reloj para comunicación serie sincrónica." },
    "PB5": { categoria: "com", descripcion: "I2C1_SMBA / SPI3_MOSI: Bus de datos para sensores o periféricos de alta velocidad." },
    "PB7": { categoria: "com", descripcion: "I2C1_SDA: Línea de datos para el bus I2C (sensores de temperatura, acelerómetros, etc.)." },
    "PB9": { categoria: "com", descripcion: "I2C1_SDA / CAN1_TX: Pin multifunción para bus I2C o comunicación CAN1." },
    "PE1": { categoria: "com", descripcion: "FSMC_NBL1 / EVENTOUT: Pin de control de byte alto para bus de memoria externa o disparo de eventos internos." },

    "PB15": { categoria: "com", descripcion: "SPI2_MOSI / I2S2_SD: Pin de salida de datos para bus SPI o audio digital (I2S)." },
    "PD9": { categoria: "com", descripcion: "FSMC_D14: Pin de datos para bus de memoria externa o control de LCD paralelo." },
    "PD11": { categoria: "com", descripcion: "FSMC_A16: Pin de dirección para direccionamiento de memorias de gran capacidad." },
    "PD13": { categoria: "timers", descripcion: "TIM4_CH2: Salida de Timer 4. Ideal para generar señales PWM (Motores/LEDs)." },
    "PD15": { categoria: "timers", descripcion: "TIM4_CH4: Salida de Timer 4. Cuarto canal de comparación/captura." },
    "PC7": { categoria: "timers", descripcion: "TIM8_CH2 / I2S3_MCK: Reloj maestro para audio digital de alta fidelidad." },
    "PC9": { categoria: "timers", descripcion: "TIM8_CH4 / SDIO_D1: Bus de datos para tarjetas SD o Timers avanzados." },
    "PA9 TX1": { categoria: "com", descripcion: "USART1_TX: Transmisión serie de alta velocidad. Suele ir al conversor USB-Serial." },
    "PA11": { categoria: "com", descripcion: "USB_DM: Línea de datos negativa (D-) del puerto USB nativo de la F407." },
    "PA15": { categoria: "debug", descripcion: "JTDI / SPI3_NSS: Pin de entrada de datos JTAG o selección de esclavo para SPI3." },
    "PC11": { categoria: "com", descripcion: "UART4_RX / SDIO_D3: Recepción de datos serie o bus de datos para SD." },
    "PD0": { categoria: "com", descripcion: "CAN1_RX: Recepción de datos para bus CAN (comunicación automotriz/industrial)." },
    "PD2": { categoria: "com", descripcion: "UART5_RX / SDIO_CMD: Comando para bus SD o recepción de datos serie." },
    "PD4": { categoria: "com", descripcion: "USART2_RTS: Control de flujo (Request To Send) para comunicación serie robusta." },
    "PD6": { categoria: "com", descripcion: "USART2_RX: Recepción de datos serie (UART) del segundo puerto." },
    "PB3": { categoria: "debug", descripcion: "JTDO / SPI3_SCK: Pin de salida de datos JTAG o reloj para el bus SPI3." },
    "PB6": { categoria: "com", descripcion: "I2C1_SCL: Línea de reloj para el bus I2C (Sensores/Memorias EEPROM)." },
    "PB8": { categoria: "com", descripcion: "I2C1_SCL / CAN1_RX: Pin multifunción; suele usarse como reloj I2C o entrada CAN1." },
    "PE0": { categoria: "com", descripcion: "FSMC_NBL0: Pin de control de byte bajo para bus de datos de memorias externas." },

    "VDDA": { categoria: "power", descripcion: "VCC Analógico: Alimentación para los conversores ADC y DAC. Debe ser estable para evitar ruido en las mediciones." },
    "PB14": { categoria: "com", descripcion: "SPI2_MISO / TIM1_CH2N: Salida de datos SPI o canal de timer con salida complementaria." },
    "PB12": { categoria: "com", descripcion: "SPI2_NSS / CAN2_RX: Selección de esclavo SPI o recepción de datos para el segundo bus CAN." },
    "PB10": { categoria: "com", descripcion: "I2C2_SCL / USART3_TX: Reloj para el segundo bus I2C o transmisión serie del puerto 3." },
    "PE14": { categoria: "timers", descripcion: "TIM1_CH4: Canal 4 del Timer 1 (Timer de control avanzado para motores)." },
    "PE12": { categoria: "timers", descripcion: "TIM1_CH3N: Salida complementaria del Canal 3 del Timer 1. Soporta generación de señales PWM complejas." },
    "PE10": { categoria: "timers", descripcion: "TIM1_CH2N: Salida complementaria del Canal 2 del Timer 1. Usado para control de potencia y temporización de precisión." },
    "PE8": { categoria: "timers", descripcion: "TIM1_CH1N: Salida complementaria del Canal 1 del Timer 1." },
    "PB1": { categoria: "analog", descripcion: "ADC1_IN9 / TIM3_CH4: Entrada analógica 9 o salida de timer de propósito general." },
    "PC5": { categoria: "analog", descripcion: "ADC1_IN15: Entrada analógica 15. Ideal para leer sensores de voltaje o corriente." },
    "PA7": { categoria: "analog", descripcion: "ADC1_IN7 / SPI1_MOSI: Entrada analógica o bus de datos para periféricos rápidos." },
    "PA5": { categoria: "analog", descripcion: "ADC1_IN5 / DAC_OUT2: Pin crítico: puede leer señales analógicas o GENERAR voltajes (DAC)." },
    "PA3": { categoria: "analog", descripcion: "ADC1_IN3 / USART2_RX: Entrada analógica o recepción de datos serie del puerto 2." },
    "PA1": { categoria: "analog", descripcion: "ADC1_IN1 / TIM2_CH2: Entrada analógica o canal de timer de 32 bits." },
    "PC3": { categoria: "analog", descripcion: "ADC1_IN13 / SPI2_MOSI: Entrada analógica o bus de datos SPI secundario." },
    "PC1": { categoria: "analog", descripcion: "ADC1_IN11: Entrada analógica de propósito general." },
    "PC13": { categoria: "power", descripcion: "RTC_AF1: Pin del reloj de tiempo real (RTC). Ojo: tiene un límite de corriente bajísimo." },
    "PE5": { categoria: "timers", descripcion: "TIM9_CH1 / TRACED2: Timer de alta velocidad o salida de traza para depuración avanzada." },
    "PE3": { categoria: "com", descripcion: "FSMC_A19: Pin de dirección para control de memorias externas (SRAM/NOR/NAND)." },

    "VREF": { categoria: "analog", descripcion: "VREF+: Voltaje de referencia positivo para ADC/DAC. De este valor depende la precisión de tus mediciones analógicas." },
    "PB13": { categoria: "com", descripcion: "SPI2_SCK / USB_OTG_HS_VBUS: Reloj para bus SPI2 o detección de alimentación para USB High Speed." },
    "PB11": { categoria: "com", descripcion: "I2C2_SDA / USART3_RX: Línea de datos para bus I2C o recepción serie del puerto 3." },
    "PE15": { categoria: "timers", descripcion: "TIM1_BKIN: Entrada de 'Break'. Permite detener todas las salidas del Timer 1 instantáneamente por seguridad." },
    "PE13": { categoria: "timers", descripcion: "TIM1_CH3: Canal 3 del Timer 1. Salida PWM de alta velocidad para control de potencia." },
    "PE11": { categoria: "timers", descripcion: "TIM1_CH2: Canal 2 del Timer 1. Usado frecuentemente en control de motores y servos." },
    "PE9": { categoria: "timers", descripcion: "TIM1_CH1: Canal 1 del Timer 1. Pin principal de salida para funciones de temporización avanzada." },
    "PE7": { categoria: "timers", descripcion: "TIM1_ETR: External Trigger. Permite sincronizar el Timer 1 con una señal externa a la placa." },
    "PB0": { categoria: "analog", descripcion: "ADC1_IN8 / TIM3_CH3: Entrada analógica canal 8 o salida de timer de propósito general." },
    "PC4": { categoria: "analog", descripcion: "ADC1_IN14: Entrada analógica para lectura de sensores de voltaje o señales variables." },
    "PA6": { categoria: "analog", descripcion: "ADC1_IN6 / SPI1_MISO: Entrada analógica o salida de datos (Master In Slave Out) para bus SPI." },
    "PA4": { categoria: "analog", descripcion: "ADC1_IN4 / DAC_OUT1: Pin con salida analógica real (DAC). Permite generar formas de onda o audio." },
    "PA2": { categoria: "analog", descripcion: "ADC1_IN2 / USART2_TX: Entrada analógica o transmisión de datos serie del segundo puerto." },
    "PA0": { categoria: "power", descripcion: "WKUP / ADC1_IN0: Pin de Wake-up. El único capaz de despertar al microcontrolador del modo Standby." },
    "PC2": { categoria: "analog", descripcion: "ADC1_IN12 / SPI2_MISO: Entrada analógica o bus de datos SPI secundario." },
    "PC0": { categoria: "analog", descripcion: "ADC1_IN10: Entrada analógica de propósito general para sensores externos." },
    "PE6": { categoria: "timers", descripcion: "TIM9_CH2: Canal 2 del Timer 9. Útil para mediciones de frecuencia o PWM rápido." },
    "PE4": { categoria: "com", descripcion: "FSMC_A20: Pin de dirección para el bus de memoria externa (SRAM/LCD)." },
    "PE2": { categoria: "com", descripcion: "FSMC_A23: Pin de dirección de alto orden para direccionamiento de memorias grandes." },
        
    "PWR POS": { categoria: "power", descripcion: "VIN / VCC: Entrada de alimentación principal positiva. Normalmente acepta entre 5V y 12V (dependiendo del regulador de la placa) para energizar todo el sistema." },
    "PWR NEG": { categoria: "power", descripcion: "GND / Ground: Referencia negativa o tierra común. Es el punto de retorno de corriente para todos los componentes de la placa." },
};
